# Configuration for everything but the keys

# Config for OpenMHZ scanning
[radio]
"filterCode" = [2815, 2817, 2821, 2807]
"filterType" = "talkgroup"
"filterName" = "OpenMHZ"
"filterStarred" = false
"shortName" = "psern"
# DEBUG CONFIG TO GET A LOT OF RESPONSES
# "filterCode": "",
# "filterType": "all",
# "filterName": "OpenMHZ",
# "filterStarred": False,
# "shortName": "psern",

# Config for how to tweet
[tweet]
call = "{} second encrypted call at {}"
names = "#{}: {}"
hashtags = "#SeattleEncryptedComms"
padding = 20

[general]
call_threshold = 1
timezone = "US/Pacific"
window_minutes = 5
debug = false
